"""Add approval status string

Revision ID: 1833997e7822
Revises: 4ac51a00af26
Create Date: 2026-08-03 12:39:44.652470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1833997e7822'
down_revision: Union[str, Sequence[str], None] = '4ac51a00af26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('approval_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'approval_status')
    # ### end Alembic commands ###
